EmbodiedSuffering_Toolkit-#3-CountryMaterial
BHoM/EmbodiedSuffering_Toolkit pull request #7
Opened 2022-06-16 20:35 UTC by kayleighhoude

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #3  #5

Addition of global countries enum and Material Import Mix object

### Test files

### Changelog

### Additional comments

2022-06-16 21:35 UTC, michaelhoehn requested changes

2022-06-16 21:35 UTC, michaelhoehn commented on EmbodiedSuffering_oM/Elements/MaterialImportSources.cs
> +        public virtual Countries ExportCountries { get; set; } = Countries.Undefined;
The property name and description imply a list should be used here. Is that the intention?

2022-06-16 21:35 UTC, michaelhoehn commented
@BHoMBot check project-compliance

2022-06-16 21:36 UTC, michaelhoehn commented
@BHoMBot check compliance

2022-06-16 21:40 UTC, michaelhoehn commented
@kayleighhoude branch compliance has failed here. It's not a required check for this toolkit (yet) to be merged in, but would advise in the future to follow the convention of `NameHere_Toolkit-#Issue-Name-of-the-branch` or `EmbodiedSuffering_Toolkit-#3-Country-material-additions` in this case.

2022-07-06 16:57 UTC, kayleighhoude commented
Opening new PR based on main branch with build events established

2022-07-06 16:57 UTC, closed without merging